/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import level2 from "./level2"
import HomeView from "./cui/HomeView"
import start from "./start"
import enemy from "./prefab/enemy"
import turret from "./prefab/turret"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="level2.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("level2.ts",level2);
        reg("cui/HomeView.ts",HomeView);
        reg("start.ts",start);
        reg("prefab/enemy.ts",enemy);
        reg("prefab/turret.ts",turret);
    }
}
GameConfig.init();